# Generated by Django 5.2.6 on 2025-09-22 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TLSEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=443)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndpointScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_chain', models.TextField()),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('protocol_version', models.CharField(max_length=50)),
                ('cipher_suite', models.CharField(max_length=100)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tls_tracker.tlsendpoint')),
            ],
        ),
    ]
