# Generated by Django 5.2.6 on 2025-09-22 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tls_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('scan_interval_hours', models.PositiveIntegerField(default=24)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('is_active_configuration', models.BooleanField(default=True)),
                ('cert_expiry_warning_days', models.PositiveIntegerField(default=30)),
                ('enable_email_alerts', models.BooleanField(default=False)),
                ('alert_email_addresses', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('min_tls_version', models.CharField(default='1.2', max_length=10)),
                ('require_ephemeral_keys', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='endpointscanresult',
            options={'ordering': ['-scan_date']},
        ),
        migrations.RenameField(
            model_name='endpointscanresult',
            old_name='cert_chain',
            new_name='cert_chain_raw',
        ),
        migrations.AddField(
            model_name='endpointscanresult',
            name='cert_chain_length',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='endpointscanresult',
            name='cert_expiration',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endpointscanresult',
            name='cert_issuer',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endpointscanresult',
            name='cert_serial_number',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endpointscanresult',
            name='cert_subject',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endpointscanresult',
            name='key_exchange',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='endpointscanresult',
            name='uses_ephemeral_keys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endpointscanresult',
            name='validation_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tlsendpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tlsendpoint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='endpointscanresult',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='tls_tracker.tlsendpoint'),
        ),
        migrations.AlterField(
            model_name='tlsendpoint',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tlsendpoint',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tlsendpoint',
            unique_together={('domain', 'port')},
        ),
        migrations.CreateModel(
            name='ChangeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('protocol_downgrade', 'Protocol Downgrade'), ('cipher_change', 'Cipher Suite Change'), ('cert_change', 'Certificate Change'), ('cert_expiring', 'Certificate Expiring Soon'), ('ephemeral_keys_lost', 'Lost Ephemeral Key Exchange'), ('validation_failed', 'Validation Failed')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('previous_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='tls_tracker.tlsendpoint')),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tls_tracker.endpointscanresult')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('endpoints_scanned', models.PositiveIntegerField(default=0)),
                ('changes_detected', models.PositiveIntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tls_tracker.scanconfiguration')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
