# Generated by Django 5.2.6 on 2025-09-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tls_tracker', '0002_scanconfiguration_alter_endpointscanresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointscanresult',
            name='is_self_signed',
            field=models.BooleanField(default=False),
        ),
    ]
